name: Deploy Odoo

on:
  push:
    branches:
      - main  # Jalan saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/odoo/training_18/addons/training_18
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
